### ISSUE TITLE
Unable to install occmodel with PIP

### ISSUE THREAD

**Issue by firegurafiku** [tenko/occmodel#3]
I'm trying to install occmodel with `pip install occmodel` and get the following error message:
```text
Downloading/unpacking occmodel
  Downloading occmodel-0.1.0.tar.gz (270kB): 270kB downloaded
  Running setup.py (path:/tmp/pip-build-niH2pa/occmodel/setup.py) egg_info for package occmodel
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-niH2pa/occmodel/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-niH2pa/occmodel/setup.py'
```

It seems that the tarball downloaded from PyPI doesn't contain `setup.py` file, it's named `setup_build.py` instead. Have you ever checked whether the library can be installed from PyPI?

**Comment by tenko** [comment]
Yes, It is wrongly called 'setup_build.py'.

It needs to compile and link against OpenCascade/OCE and system libraries, so it only a 'source' distribution anyway, and can not be installed directly. Most likely it needs tweaking to get build
depending on the platform and where the libraries are installed.

In the fork : https://github.com/colonelzentor/occmodel, there is an effort to improve the
build process which you might look at (not tested)

**Comment by mikedh** [comment]
If you're on Ubuntu 14.04, I forked/repackaged to fix pip install:
https://github.com/mikedh/occmodel
